### PR TITLE
Meta fixes

### PR DESCRIPTION
**Pull request by midsbie**

### CODE REVIEW

**Review by kujenga — APPROVED** [review]
Looks good!

**Comment by kujenga** [comment]
Hmm, it looks like these build failures are not transient issues but rather they seem to be legitimate failures because certain things still rely on jQuery. @miguel-guedes are you able to reproduce those locally?

**Comment by miguel-guedes** [comment]
@kujenga I think there are transient issues at play here too but you're right in that this PR is afflicted by the darned jQuery issue.  Would it be okay to merge this intermediary PR as-is now knowing that the next PR fixes the current outstanding issue?

**Comment by miguel-guedes** [comment]
Closing in favour of https://github.com/dossier/html-highlighter/pull/30

**Pull request closed without merging**
