### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by miguel-guedes**
Fixes an issue whereby selecting text that span multiple elements (say, two or
more paragraphs), resulted in an exception being produced.

### CODE REVIEW

**Comment by miguel-guedes** [comment]
@kujenga and @jasonbriggs : Don't merge this PR until the latest work is in.

**Comment by kujenga** [comment]
@miguel-guedes it looks like this PR needs a rebase. Are there any other changes you plan to make here or is this ready for review?

**Comment by jasonbriggs** [comment]
As discussed with @miguel-guedes, closing this out in favor of https://github.com/dossier/html-highlighter/pull/30.

**Comment by miguel-guedes** [comment]
@jasonbriggs: you closed the wrong PR :)

**Comment by miguel-guedes** [comment]
This is the PR that was supposed to be closed: #29

**Comment by jasonbriggs** [comment]
Oh, I thought you said it was okay to discard the `improvements` PR, thought that was this one, sorry about that! 😄

**Comment by miguel-guedes** [comment]
@jasonbriggs: this PR can remain closed!

**Pull request closed without merging**
